// <auto-generated />
using System;
using Etkincity.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Etkincity.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260426122252_FixDecimalPrecision")]
    partial class FixDecimalPrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Etkincity.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            Date = new DateTime(2026, 7, 15, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tarihi Akdamar Adasý'nda muhteþem bir yaz konseri sizleri bekliyor.",
                            ImageUrl = "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?auto=format&fit=crop&w=800&q=80&sig=1",
                            Location = "Akdamar Adasý",
                            Price = 250m,
                            Title = "Akdamar Adasý Yaz Konseri"
                        },
                        new
                        {
                            Id = 2,
                            Category = 2,
                            Date = new DateTime(2026, 5, 10, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vanspor'un kritik þampiyonluk mücadelesinde takýmýný yalnýz býrakma!",
                            ImageUrl = "https://images.unsplash.com/photo-1504450758481-7338eba7524a?auto=format&fit=crop&w=800&q=80&sig=2",
                            Location = "Van Atatürk Stadyumu",
                            Price = 100m,
                            Title = "Vanspor FK Þampiyonluk Maçý"
                        },
                        new
                        {
                            Id = 3,
                            Category = 3,
                            Date = new DateTime(2026, 6, 5, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Shakespeare'in ölümsüz eseri Hamlet, modern ve farklý bir yorumla Van'da.",
                            ImageUrl = "https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=800&q=80&sig=3",
                            Location = "Van Devlet Tiyatrosu",
                            Price = 150m,
                            Title = "Hamlet - Modern Uyarlama"
                        },
                        new
                        {
                            Id = 4,
                            Category = 4,
                            Date = new DateTime(2026, 8, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Müzik, eðlence ve yarýþmalarýn olduðu en büyük gençlik festivali.",
                            ImageUrl = "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=800&q=80&sig=4",
                            Location = "Edremit Sahili",
                            Price = 300m,
                            Title = "Van Gölü Geleneksel Gençlik Festivali"
                        },
                        new
                        {
                            Id = 5,
                            Category = 5,
                            Date = new DateTime(2026, 9, 10, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Yapay zeka ve gelecek hakkýnda ufuk açýcý bir söyleþi.",
                            ImageUrl = "https://images.unsplash.com/photo-1475721027187-402ad2989a3b?auto=format&fit=crop&w=800&q=80&sig=5",
                            Location = "Van Yüzüncü Yýl Üniversitesi",
                            Price = 50m,
                            Title = "Geleceðin Teknolojileri Söyleþisi"
                        },
                        new
                        {
                            Id = 6,
                            Category = 6,
                            Date = new DateTime(2026, 10, 12, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gülme garantili harika bir stand-up gösterisi.",
                            ImageUrl = "https://images.unsplash.com/photo-1527224857853-e3748b6f4813?auto=format&fit=crop&w=800&q=80&sig=6",
                            Location = "Van Kültür Merkezi",
                            Price = 120m,
                            Title = "Doðu'nun Kahkahasý Stand-Up"
                        },
                        new
                        {
                            Id = 7,
                            Category = 7,
                            Date = new DateTime(2026, 11, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tarihin derinliklerinden gelen muazzam eserler sergisi.",
                            ImageUrl = "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?auto=format&fit=crop&w=800&q=80&sig=7",
                            Location = "Van Müzesi",
                            Price = 0m,
                            Title = "Urartu Tarihi Resim Sergisi"
                        },
                        new
                        {
                            Id = 8,
                            Category = 8,
                            Date = new DateTime(2026, 4, 25, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gözleriyle ünlü Van kedilerinin eðlenceli podyum heyecaný.",
                            ImageUrl = "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=800&q=80&sig=8",
                            Location = "Van Kedisi Araþtýrma Merkezi",
                            Price = 30m,
                            Title = "Van Kedisi Güzellik Yarýþmasý"
                        },
                        new
                        {
                            Id = 9,
                            Category = 1,
                            Date = new DateTime(2026, 5, 2, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bölgenin en sevilen rock gruplarý sahnede.",
                            ImageUrl = "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?auto=format&fit=crop&w=800&q=80&sig=9",
                            Location = "Van Kalesi Açýk Hava Sahnesi",
                            Price = 180m,
                            Title = "Kýþa Veda Rock Konseri"
                        },
                        new
                        {
                            Id = 10,
                            Category = 2,
                            Date = new DateTime(2026, 7, 22, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Türkiye'nin dört bir yanýndan gelen sporcularla yüzme maratonu.",
                            ImageUrl = "https://images.unsplash.com/photo-1504450758481-7338eba7524a?auto=format&fit=crop&w=800&q=80&sig=10",
                            Location = "Tuþba Sahili",
                            Price = 0m,
                            Title = "Van Gölü Yüzme Maratonu"
                        },
                        new
                        {
                            Id = 11,
                            Category = 4,
                            Date = new DateTime(2026, 6, 15, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Van kahvaltýsý ve eþsiz lezzetlerin sunulduðu yemek festivali.",
                            ImageUrl = "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=800&q=80&sig=11",
                            Location = "Van Fuar Alaný",
                            Price = 80m,
                            Title = "Bölgesel Lezzetler Festivali"
                        },
                        new
                        {
                            Id = 12,
                            Category = 1,
                            Date = new DateTime(2026, 9, 25, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Senfoni orkestrasý eþliðinde unutulmaz klasik müzik ziyafeti.",
                            ImageUrl = "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?auto=format&fit=crop&w=800&q=80&sig=12",
                            Location = "Van Kültür Merkezi",
                            Price = 200m,
                            Title = "Klasik Müzik Akþamý"
                        },
                        new
                        {
                            Id = 13,
                            Category = 5,
                            Date = new DateTime(2026, 10, 5, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sevilen yazarlarla interaktif söyleþi ve imza günü.",
                            ImageUrl = "https://images.unsplash.com/photo-1475721027187-402ad2989a3b?auto=format&fit=crop&w=800&q=80&sig=13",
                            Location = "Van Ýl Halk Kütüphanesi",
                            Price = 0m,
                            Title = "Yazar Buluþmalarý ve Ýmza Günü"
                        },
                        new
                        {
                            Id = 14,
                            Category = 3,
                            Date = new DateTime(2026, 1, 15, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Eðlenceli ve heyecanlý artistik buz pateni gösterisi.",
                            ImageUrl = "https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=800&q=80&sig=14",
                            Location = "Van AVM Buz Pisti",
                            Price = 100m,
                            Title = "Buz Pateni Gösterisi"
                        },
                        new
                        {
                            Id = 15,
                            Category = 8,
                            Date = new DateTime(2026, 8, 10, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Yýldýzlarýn altýnda, Van gölü kenarýnda klasik film gösterimi.",
                            ImageUrl = "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=800&q=80&sig=15",
                            Location = "Edremit Kent Ormaný",
                            Price = 60m,
                            Title = "Açýk Hava Sinema Gecesi"
                        });
                });

            modelBuilder.Entity("Etkincity.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ReservationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TicketCount")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Etkincity.Models.Reservation", b =>
                {
                    b.HasOne("Etkincity.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
