// <auto-generated />
using System;
using Etkincity.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Etkincity.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260514085304_AddSeatSelection")]
    partial class AddSeatSelection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Etkincity.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            Date = new DateTime(2026, 7, 15, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tarihi Akdamar Adası'nda muhteşem bir yaz konseri sizleri bekliyor.",
                            ImageUrl = "https://picsum.photos/seed/konser1/600/400",
                            Location = "Akdamar Adası",
                            Price = 250m,
                            Title = "Akdamar Adası Yaz Konseri"
                        },
                        new
                        {
                            Id = 2,
                            Category = 2,
                            Date = new DateTime(2026, 5, 10, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vanspor'un kritik şampiyonluk mücadelesinde takımını yalnız bırakma!",
                            ImageUrl = "https://picsum.photos/seed/spor1/600/400",
                            Location = "Van Atatürk Stadyumu",
                            Price = 100m,
                            Title = "Vanspor FK Şampiyonluk Maçı"
                        },
                        new
                        {
                            Id = 3,
                            Category = 3,
                            Date = new DateTime(2026, 6, 5, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Shakespeare'in ölümsüz eseri Hamlet, modern ve farklı bir yorumla Van'da.",
                            ImageUrl = "https://picsum.photos/seed/tiyatro1/600/400",
                            Location = "Van Devlet Tiyatrosu",
                            Price = 150m,
                            Title = "Hamlet - Modern Uyarlama"
                        },
                        new
                        {
                            Id = 4,
                            Category = 4,
                            Date = new DateTime(2026, 8, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Müzik, eğlence ve yarışmaların olduğu en büyük gençlik festivali.",
                            ImageUrl = "https://picsum.photos/seed/festival1/600/400",
                            Location = "Edremit Sahili",
                            Price = 300m,
                            Title = "Van Gölü Geleneksel Gençlik Festivali"
                        },
                        new
                        {
                            Id = 5,
                            Category = 5,
                            Date = new DateTime(2026, 9, 10, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Yapay zeka ve gelecek hakkında ufuk açıcı bir söyleşi.",
                            ImageUrl = "https://picsum.photos/seed/soylesi1/600/400",
                            Location = "Van Yüzüncü Yıl Üniversitesi",
                            Price = 50m,
                            Title = "Geleceğin Teknolojileri Söyleşisi"
                        },
                        new
                        {
                            Id = 6,
                            Category = 6,
                            Date = new DateTime(2026, 10, 12, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gülme garantili harika bir stand-up gösterisi.",
                            ImageUrl = "https://picsum.photos/seed/standup1/600/400",
                            Location = "Van Kültür Merkezi",
                            Price = 120m,
                            Title = "Doğu'nun Kahkahası Stand-Up"
                        },
                        new
                        {
                            Id = 7,
                            Category = 7,
                            Date = new DateTime(2026, 11, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tarihin derinliklerinden gelen muazzam eserler sergisi.",
                            ImageUrl = "https://picsum.photos/seed/sergi1/600/400",
                            Location = "Van Müzesi",
                            Price = 0m,
                            Title = "Urartu Tarihi Resim Sergisi"
                        },
                        new
                        {
                            Id = 8,
                            Category = 8,
                            Date = new DateTime(2026, 4, 25, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gözleriyle ünlü Van kedilerinin eğlenceli podyum heyecanı.",
                            ImageUrl = "https://picsum.photos/seed/kedi1/600/400",
                            Location = "Van Kedisi Araştırma Merkezi",
                            Price = 30m,
                            Title = "Van Kedisi Güzellik Yarışması"
                        },
                        new
                        {
                            Id = 9,
                            Category = 1,
                            Date = new DateTime(2026, 5, 2, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bölgenin en sevilen rock grupları sahnede.",
                            ImageUrl = "https://picsum.photos/seed/rock1/600/400",
                            Location = "Van Kalesi Açık Hava Sahnesi",
                            Price = 180m,
                            Title = "Kışa Veda Rock Konseri"
                        },
                        new
                        {
                            Id = 10,
                            Category = 2,
                            Date = new DateTime(2026, 7, 22, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Türkiye'nin dört bir yanından gelen sporcularla yüzme maratonu.",
                            ImageUrl = "https://picsum.photos/seed/yuzme1/600/400",
                            Location = "Tuşba Sahili",
                            Price = 0m,
                            Title = "Van Gölü Yüzme Maratonu"
                        },
                        new
                        {
                            Id = 11,
                            Category = 4,
                            Date = new DateTime(2026, 6, 15, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Van kahvaltısı ve eşsiz lezzetlerin sunulduğu yemek festivali.",
                            ImageUrl = "https://picsum.photos/seed/yemek1/600/400",
                            Location = "Van Fuar Alanı",
                            Price = 80m,
                            Title = "Bölgesel Lezzetler Festivali"
                        },
                        new
                        {
                            Id = 12,
                            Category = 1,
                            Date = new DateTime(2026, 9, 25, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Senfoni orkestrası eşliğinde unutulmaz klasik müzik ziyafeti.",
                            ImageUrl = "https://picsum.photos/seed/klasik1/600/400",
                            Location = "Van Kültür Merkezi",
                            Price = 200m,
                            Title = "Klasik Müzik Akşamı"
                        },
                        new
                        {
                            Id = 13,
                            Category = 5,
                            Date = new DateTime(2026, 10, 5, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sevilen yazarlarla interaktif söyleşi ve imza günü.",
                            ImageUrl = "https://picsum.photos/seed/yazar1/600/400",
                            Location = "Van İl Halk Kütüphanesi",
                            Price = 0m,
                            Title = "Yazar Buluşmaları ve İmza Günü"
                        },
                        new
                        {
                            Id = 14,
                            Category = 3,
                            Date = new DateTime(2026, 1, 15, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Eğlenceli ve heyecanlı artistik buz pateni gösterisi.",
                            ImageUrl = "https://picsum.photos/seed/buz1/600/400",
                            Location = "Van AVM Buz Pisti",
                            Price = 100m,
                            Title = "Buz Pateni Gösterisi"
                        },
                        new
                        {
                            Id = 15,
                            Category = 8,
                            Date = new DateTime(2026, 8, 10, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Yıldızların altında, Van gölü kenarında klasik film gösterimi.",
                            ImageUrl = "https://picsum.photos/seed/sinema1/600/400",
                            Location = "Edremit Kent Ormanı",
                            Price = 60m,
                            Title = "Açık Hava Sinema Gecesi"
                        });
                });

            modelBuilder.Entity("Etkincity.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ReservationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SelectedSeat")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("TicketCount")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Etkincity.Models.UserEventView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ViewDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("UserEventViews");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Etkincity.Models.Reservation", b =>
                {
                    b.HasOne("Etkincity.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Etkincity.Models.UserEventView", b =>
                {
                    b.HasOne("Etkincity.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
